import { createSlice } from '@reduxjs/toolkit';
const counterSlice = createSlice({
    name: 'counter',
    initialState: { value: 0 },
    reducers: {
      increment: (state,action) => {
        debugger
        state.value = state.value + action.payload;
      },
      decrement: (state) => {
        state.value -= 1;
      },
    },
  });
  export const { increment, decrement } = counterSlice.actions;

  // Export actions generated by createSlice
  export default counterSlice.reducer;